### ISSUE TITLE
Drawn lines not dynamic? 

### ISSUE THREAD

**Issue by ThirdGhostHand** [kdeloach/react-lineto#21]
I'm using a couple lines similar to this 
```<LineTo from="img" to="img2" borderColor="white" borderWidth={4} />```
When rendered initially, the lines show up great, but if I move the images around say with animation or just by moving their relative position on screen by changing the size of the window, the lines stay where they were when first rendered, rather than following the images around. Am I doin' something wrong?

**Comment by kdeloach** [comment]
This is by design. The line component is rendered relative to the window using absolute positioning. To update the line you need to trigger a render whenever the referenced objects change position.

Here's some reference code which does exactly this, from an earlier commit:
https://github.com/kdeloach/react-lineto/blob/dc8059361bfc490f250a17cf207dd96c794accf4/demo/index.jsx#L64

**Comment by ThirdGhostHand** [comment]
That seems to have fixed it right up! Thank you.
