### ISSUE TITLE
Could not find a declaration file for module 'react-lineto'. 

### ISSUE THREAD

**Issue by wisdom-17** [kdeloach/react-lineto#24]
Hi,

I am trying to use this package in my ReactJS application. I took the following steps to install the package:
1) Added "react-lineto": "3.1.3" to my package.json file
2) Ran "yarn install"
3) Added some code using the SteppedLineTo feature from the library.

No lines appear on my page. 

My IDE highlights the import statement (import {SteppedLineTo} from "react-lineto";) with the following message:
Could not find a declaration file for module 'react-lineto'. '/Users/bob/Sites/audience-builder-frontend/node_modules/react-lineto/dist/react-lineto.js' implicitly has an 'any' type.
  Try `npm install @types/react-lineto` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-lineto';`

**Comment by swedishgoodbye** [comment]
I was having a similar issue. Had set things up within my react app pretty much following the example set by the demo, and the code given in the readme but was not able to produce any line. 

Just now after applying "delay: true" to the line's style I was able to get it to work, without that bit I could not find a way to make it visible. Not sure if that's the intention, or a misunderstanding of the package's usage but potentially should be explained better in the docs if intentional.

**Comment by kdeloach** [comment]
> Just now after applying "delay: true" to the line's style I was able to get it to work, without that bit I could not find a way to make it visible. Not sure if that's the intention, or a misunderstanding of the package's usage but potentially should be explained better in the docs if intentional.

It sounds like you are trying to draw the line before your target element exists. Hard to say without viewing your code, but that explains why `delay` fixes it. I don't know how to solve for this besides throwing an exception if the target element doesn't exist yet.

**Comment by kdeloach** [comment]
This project does not have TypeScript definitions. Feel free to open a PR to submit definitions. Closing.
