### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by kdeloach** [kdeloach/react-lineto#5]

**Comment by hamczu** [comment]
What do you think about using 'prop-types' repo instead of importing them from React? React@15 warns about that: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

**Comment by jbccollins** [comment]
Please. This is broken with React 16

**Comment by kdeloach** [comment]
I'll take a look at it later tonight.

**Comment by jbccollins** [comment]
@kdeloach  Cool. Made a PR. Couldn't get the demo to run using a CentOS VM. Probably something to do with my hosts file or whatever.

**Comment by kdeloach** [comment]
Release 2.0.0 has been published. Thanks!
